---
- name: "CONFIGURATION OF WEBSERVER"
  hosts: server[1-1245]
  tasks:
  - name: "Installing of Apache Webserver"
    yum:
      name: httpd
      state: installed
  - name: "Starting the Webserver Service Permanently"
    service: 
      name: httpd
      state: started
      enabled: true
  - name: "Allowing http port on firewall"
    firewalld:
      state: enabled
      service: http
      immediate: true
      permanent: true
  - copy: 
     dest: /var/www/html/index.html
     content: 'Simple Webserver for "{{ansible_fqdn}}"'
     mode: 0644
...         
